### ISSUE TITLE
Memory Leak while using quarkus-cxf

### ISSUE THREAD

**Issue by querdenker2k** [quarkiverse/quarkus-cxf#1017]
With the current version of Quarkus 3.3.2 and the corresponding cxf Version i got a memory leak.

Here is a reproducer: https://github.com/querdenker2k/cxf-memoryleak-reproducer

There are jaxb classes hanging in jdk.internal.net.http.HttpClientImpl$SelectorManager

Probably this is the same problem as here: https://github.com/quarkiverse/quarkus-cxf/issues/992

**Comment by ppalaga** [comment]
Yes, this is defintely #992. To avoid the leak, you have several options:

A. Avoid creating the client too often, such as per request. Rather create it once at application start.
B. Configure CXF to use org.apache.cxf.transport.http.URLConnectionHTTPConduit via setting HTTPConduitFactory.class on CXF Bus. Note that in Quarkus CXF 2.3.1 and 2.2.3, we made URLConnectionHTTPConduit deafult because of this issue.
