### ISSUE TITLE
Interceptors set through `@InInterceptors` and similar annotations are not looked up the CDI container

### ISSUE THREAD

**Issue by Inithron** [quarkiverse/quarkus-cxf#1367]
I am using Quarkus CXF in version 3.10.0

Like in the [WS-Security](https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/ws-security) example I am using a WSS4JInInterceptorProducer. When the interceptor is configured in the application.properties, everything is working fine. But if the interceptor is configured via the annotation:
`@InInterceptors(interceptors = { "org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor" })`
following error occurs:
`2024-05-05 12:56:06,880 WARN  [org.apa.cxf.ws.sec.wss.WSS4JInInterceptor] (executor-thread-1) No security action was defined!`

**Comment by ppalaga** [comment]
Thanks for the report. Indeed, the use case should work.

I wonder why you prefer setting the WSS4K interceptors manually, rather than using WS-SecurityPolicy? I do not want to discredit your report, I am just curious about your motivation.

**Comment by Inithron** [comment]
The WSDLs are provided from our customers together with an interface specification where they specify if they want to have additional features like signatures, encryption, compression, etc. There are two main reasons not to use policies:
1. Due to the fact that we have not created the WSDLs, we use them without modifications and handle the additions with interceptors.
2. With this approach updates can be executed more easy when we can replace only the WSDL files without the need to add each time the policies again or merge the changes into the modified WSDL with policies.

**Comment by ppalaga** [comment]
The root cause is that CXF is not aware of CDI and is only able to instantiate the interceptors reflectively using the default constructor. In case of `org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor`, if it is specified via `@InInterceptors` instead of application.properties, the [bean producer method](https://github.com/quarkiverse/quarkus-cxf/blob/632e89b04d548e98a7dd083c6a8e1d616ef46bf9/integration-tests/ws-security/src/main/java/io/quarkiverse/cxf/it/wss/server/WSS4JInInterceptorProducer.java#L52-L72), where the bean is configured, is ignored and thus the service call fails on that missing configuration.

The fix I am working on, replaces the CXF code instantiating the interceptors with a custom CXF one, so that the beans are looked up the CDI container.
