### ISSUE TITLE
Regression: Second Webservice Config Ignored

### ISSUE THREAD

**Issue by wh81752** [quarkiverse/quarkus-cxf#162]
After pulling latest updates in today (up to revision [992436c955fb9df278834c5e69fef176c87bc2d3](https://github.com/quarkiverse/quarkus-cxf/commit/992436c955fb9df278834c5e69fef176c87bc2d3)) this configuration no longer works:

```
quarkus.cxf.path=/ws
quarkus.cxf.endpoint."/hw".implementor=io.app.ws.HelloWorldImpl       # this ws is not present any longer
quarkus.cxf.endpoint."/hw1".implementor=io.app.ws.HelloWorldImpl     # this one is and also
quarkus.cxf.endpoint."/greet".implementor=io.app.ws.GreetingImpl       # this one.
```

`HelloWorldImpl` and `GreetingImpl` implement both SEI `HelloWorld`.

**Comment by dufoli** [comment]
Yes it is expected with recent changes but what's is the purpose to have 2 route with same implementor...??
Just provide a route forwarding with Vertx...

**Comment by wh81752** [comment]
> Yes it is expected with recent changes but what's is the purpose to have 2 route with same implementor...??
Let's view it from an other angle - having a second implementor is perfectly valid and possible in native CXF (Servlet, standalone ..) - why should it then not be possible in quarkus-cxf?

**Comment by dufoli** [comment]
it come from this commit : 
https://github.com/quarkiverse/quarkus-cxf/commit/992436c955fb9df278834c5e69fef176c87bc2d3
because I add convension over configuration because I switch config by implementor.
Let me write to help me to analyse.
I am thinking to switch configuration:
if key contain a / it is a route (same than today)
if it contain dot, it is a class => 

switch from
quarkus.cxf.endpoint."/hw".implementor=io.app.ws.HelloWorldImpl
to
quarkus.cxf.endpoint."io.app.ws.HelloWorldImpl".path="/hw"

Now I put config by sei or implementor:
https://github.com/quarkiverse/quarkus-cxf/blob/master/runtime/src/main/java/io/quarkiverse/cxf/CXFRecorder.java#L98-L99

2 evolutions potential:
- I do the big switch to config by sei/implementor. So You can only have one route by implementor/sei but it mean that we can have same route (collision) for few SEI/Implementor which do not make sens and lead to other issue.
- I add a list of config and if I have few, I start a route for each one.

OK lets go with second option. it solve this ticket. Minor impact (no API break) and do not introduce issue

**Comment by wh81752** [comment]
> I am thinking to switch configuration:
> if key contain a / it is a route (same than today)
> if it contain dot, it is a class =>

```
quarkus.cxf.endpoint."/hw".implementor=io.app.ws.HelloWorldImpl              # current config style
quarkus.cxf.endpoint."io.app.ws.HelloWorldImpl".path=/hw                           # alternate config style 
```

A user could choose whether using the current config style or the "new" style.  In the example above, the route "/hw" occupied by two SEI implementations. This is usually a conflict and should either stop the build process or log a decent warning. The exception from this rule is, that the implementor is the same (as above). In that case configurations are merged internally.

The endpoint path "/hw"  is still artificial. The problem to overcome is to come up with a sensible default value in order to generate sensible config values (i.e. webservices) automatically.

Assume that this is given
```
package io.app.ws;
@WebService(..)
public class HelloWorldImpl implements HelloWorld { .. }
```

are this then good default values?

```
@WebService() => 
quarkus.cxf.endpoint."io.app.ws.HelloWorldImpl".path=/io/app/ws/HelloWorld        # (a) SEI as path

@WebService(serviceName="hw") => 
quarkus.cxf.endpoint."io.app.ws.HelloWorldImpl".path=/hw                        # (b) serviceName is used                 
```

[CXF states](https://cxf.apache.org/docs/developing-a-service.html#DevelopingaService-CreatingtheSEI) that `serviceName` 
`Specifies the name of the published service.`

**Comment by dufoli** [comment]
@wh81752 I am not happy to have a special config format for a particular case. So let s stick to current format.
can you test the branch "multiendpoints" with your original case (no modification on config)

**Comment by wh81752** [comment]
@dufoli - This is not for a special case. It's rather for my proposal #141  - how to automatically get webservices up and running with zero configuration. Just add "quarkus-cxf.jar" as dependency and voila, all annotated webservices are up and running. This works if config values can be _automatically_ generated.

**Comment by wh81752** [comment]
@dufoli  - ok, let me test branch https://github.com/quarkiverse/quarkus-cxf/tree/multiendpoints , pls standby,

**Comment by wh81752** [comment]
https://github.com/quarkiverse/quarkus-cxf/tree/multiendpoints => works fine with my test setup, i.e.
```
quarkus.cxf.path=/ws
quarkus.cxf.endpoint."/hw".implementor=io.app.ws.HelloWorldImpl
quarkus.cxf.endpoint."/hw1".implementor=io.app.ws.HelloWorldImpl
quarkus.cxf.endpoint."/greet".implementor=io.app.ws.GreetingImpl
```
