### ISSUE TITLE
Contract first (wsdl)?

### ISSUE THREAD

**Issue by famod** [quarkiverse/quarkus-cxf#165]
It's pretty common to have a wsdl file first, generating the stubs via e.g. `cxf-codegen-plugin` in Maven, instead of writing it all by hand (although you can of course go this way instead, "code first").

Is this supported by this extension? Current documentation doesn't mention it.

**Comment by dufoli** [comment]
yes it is supported. You have even an example in integration-test... Documentation is pretty young and we will focus to improove it on next iteration.

**Comment by famod** [comment]
Ok thanks, I'll have a look at the IT.

**Comment by famod** [comment]
Btw, what's the preferred way to discuss this extension? Issues? Quarkus Zulip?

PS: I suggest to start using GitHub milestones to assign issues/PRs to releases.

**Comment by dufoli** [comment]
issue is fine.

I have exactly the same question with quarkus team....zulip do not get response (except when I tag each member but I found that very annoying for them). Currently it is like throwing bottle in the sea.  Quarkus issue is just a big joke. Too much ticket. No cleaning. I guess that there is no grooming to cleanup tickets.
I am still learning what is the best way to communicate. Maybe mailing list is better to work with quarkus team.

If your need is only related this extension, I guess that issue is fine because here we have very few issue and I try to avoid to keep issue that is not relevant. because in zulip the message get lost in the continuous flow of arrival of message. If I stop to go on zulip one week, I see that I miss 3k message it is too much to be readable... even if mention help a lot.

About milestone, I do most of ticket and I do not plan to work on a particular point in advance.

It is passion and free time which lead me there. I am not paid so priority and milestone is far from my concern. I do that with the team I manage for my real job ;-)
here it is just project with no pressure.

**Comment by famod** [comment]
@dufoli
> issue is fine

> because in zulip the message get lost in the continuous flow of arrival of message.

Ok. I was just wondering whether a dedicated zulip channel per extension would make any sense (on Quarkus Zulip).

> I have exactly the same question with quarkus team....zulip do not get response (except when I tag each member but I found that very annoying for them). Currently it is like throwing bottle in the sea.

Well, the no so big Quarkus core team is kind of overwhelmed by their success.
Still, IMO, in most cases you get rather quick feedback.

> I guess that there is no grooming to cleanup tickets.

I do see members like Georgios pinging issue authors from time to time to find and close stale issues.
But I agree that there is a staggering amount of open issues (many being outdated, I guess, but I might be wrong).

> I am still learning what is the best way to communicate. Maybe mailing list is better to work with quarkus team.

I can relate to that. I intuitively post on Zulip because I find it more convenient than the mailing list, but a couple of times I should have posted to the list instead. 🤷‍♂️ 

> About milestone, I do most of ticket and I do not plan to work on a particular point in advance.

> It is passion and free time which lead me there. I am not paid so priority and milestone is far from my concern. I do that with the team I manage for my real job ;-)
> here it is just project with no pressure.

Well, the same applies to me and https://github.com/gitflow-incremental-builder/gitflow-incremental-builder, which I also don't get paid for.
For me, milestone assigements make my life as the maintainer actually _easier_ and user can see much better what's in a release, e.g: https://github.com/gitflow-incremental-builder/gitflow-incremental-builder/releases
I just have to link to the closed issues/PRs for that milestone and I'm mostly done.
And I don't feel forced to do something in a certain milestone, I can always unassign it at any time. 😉 
Anyway, it was just a suggestion. 🙂

**Comment by dufoli** [comment]
sorry it was a tuff day, I was a bit ruff but I always get complain in job and in open source project.
anyway, thanks for feedback. We have only 6 issues and most of time, it is open issue during the sprint which is bring in it. Not sure it can help. I have never used milestone, I will give a try...

**Comment by famod** [comment]
No worries, we all have those days. Thanks btw for all the work that you put/are putting into this!
