### ISSUE TITLE
@BindingType not working in native image

### ISSUE THREAD

**Issue by querdenker2k** [quarkiverse/quarkus-cxf#190]
I have a Soap 1.2 WSDL (with correct namespace). Additional i added `@BindingType(javax.xml.ws.soap.SOAPBinding.SOAP12HTTP_BINDING)` to the class.
When i run this with quarkus:dev it's working fine. I can call the service with SOAP1.2 client.
But running this in native mode says `org.apache.cxf.binding.soap.SoapFault: A SOAP 1.2 message is not valid when sent to a SOAP 1.1 only endpoint`.

Do i have to add something else for native image?

**Comment by querdenker2k** [comment]
I am confused about this test: `https://github.com/quarkiverse/quarkus-cxf/blob/master/integration-tests/src/test/java/io/quarkiverse/it/cxf/GreetingWebServiceImplTestIT.java`
Why is in the service call test text/xml returned which is soap1.1, but in the ServiceImpl is the Soap1.2 BindingType annotation?
Is this correct?

**Comment by shumonsharif** [comment]
Hi @querdenker2k Do you have a reproducer project available?  Your issue may be local to your environment - I have previously and successfully generated native images that support the SOAP 1.2 binding.

Regarding the integration test, I think CXF Soap 1.2 endpoints can process Soap 1.1 payloads (though not vice-versa), which is why there are no issues there.

**Comment by querdenker2k** [comment]
Its working now, but i dont know why, it must be because of any transitive dependencies i removed.
