### ISSUE TITLE
Injected CXFClientInfo does not reflect the wsdl and client-endpoint-url set in application.properties

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#491]
I am about to add a test case in an upcoming PR.

Another related issue is that it currently does not seem to be possible to inject two separate CXFClientInfos that implement the same service interface, but point at different client-endpoint-urls. I wonder whether this can be implemented at all?

**Comment by shumonsharif** [comment]
Hi @ppalaga If I understood your concern correctly, it should certainly be doable ... from the docs:

https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/client.html

"Default configurations must be unique per SEI while it is otherwise perfectly valid to have multiple client configuration units per SEI .... 

Notice the absence of property service-interface in quarkus.cxf.client."my-featured-fruitservice-client" because this configuration is meant to be an alternative to the default configuration."

**Comment by ppalaga** [comment]
@shumonsharif the docs is about configuring and injecting clients. That works as documented. 

What does not work is getting the configured endpoint URL and WSDL URL throught an injected CXFClientInfo. Here is my attempt to add a test: https://github.com/quarkiverse/quarkus-cxf/pull/488/commits/85bece26ab45abf0f0a5ff40495b0104824d55e3#diff-589b1a55c42e5a4857b144ce0ee1b076ffa7d5c8c81e941bd404092a4b942dbfR76-R113
The injected CXFClientInfo always contains some default URLs.

As for the second problem, it looks like I can only get just a single CXFClientInfo per SEI, regardless how may clients for the same implementation I have. That's a bit limiting, IMO. 
I wonder whether selecting CXFClientInfo should not work in the same way like selecting a client? - i.e. through passing the client key used in application.properties?
