### ISSUE TITLE
Alternative/Fix for CXF handlers to inject request scoped object without CDI issue/Null issue

### ISSUE THREAD

**Issue by sreekar12** [quarkiverse/quarkus-cxf#697]
We are trying to call CXF SOAP client from REST endpoint and we are trying to set a value from SOAP response in REST HTTP response headers but we are unable to do it because we are unable to inject any request scoped object in CXF SOAP handlers due to CDI.

Kindly let us know if any alternative/fix is available.

**Comment by shumonsharif** [comment]
@sreekar12 Injecting a request scoped bean in a SOAP handler seems to work fine for me.  

Did you mark your `SOAPHandler` as `@ApplicationScoped`?

**Comment by sreekar12** [comment]
Yes @shumonsharif . Can you please share the example.

**Comment by shumonsharif** [comment]
I don't have an example project handy - and I likely won't have the time to put one together this week.  I tested the CDI injection on one of my existing projects.

You're welcome to put together a simple reproducer and I can try to help with that.

**Comment by sreekar12** [comment]
@shumonsharif We are trying like below.
We are unable to inject HeaderImpl in SoapHandler class. it is giving object as null. Can you please help us on this.
Created 3 classes RequestScoped, RestService and SOAPHandler
**@RequestScoped
class HeaderImpl{
private String corrId;
// setter and getters
}
Rest service : class A{
@Inject
HeaderImpl impl;
@Path("/hi")
public Response m1(@RestHeader("correlationId") String correlationID){
impl.setCorrId(correlationID);
}
}
SoapHandler:

@ApplicationScoped
class A implements SOAPHandler<SOAPMessageContext>  {
{
@Inject
HeaderImpl impl;
public boolean handleMessage(SOAPMessageContext context) {

System.out.println(impl.getCorrelId);
}
}**

**Comment by shumonsharif** [comment]
@sreekar12 In case you need to put together a reproducer in the future, you can follow the steps below ... even though it only takes a few minutes, it helps a lot because making the time to be doing it on your behalf, can become challenging for us.
- Go to [https://code.quarkus.io/](https://code.quarkus.io/)
- Search for `quarkus-cxf` and select the checkbox
- Download the generated project zip file
- Add the classes that you pasted in your comment above into the project
- Share the project as a reproducer that demonstrates the issue you are having

Having said all that, I tried to mimic your code in the attached [code-with-quarkus.zip](https://github.com/quarkiverse/quarkus-cxf/files/10579114/code-with-quarkus.zip) project; injecting the request scoped bean is working as expected.  

If you still have an issue with this, and need further help, **kindly take the time to help us help you** by updating the attached project and demonstrating the issue you are having.  If it addresses your issue, let us know, hope this all is helpful.

**Comment by sreekar12** [comment]
Thanks @shumonsharif. It is working now
